services:
  web:
    build: .
    ports:
      - "8089:3000"
    environment:
      - APP_ENV=production
      - DB_TYPE=postgres
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    networks:
        - translations-manager-network

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    networks:
        - translations-manager-network

volumes:
  postgres_data:

networks:
  translations-manager-network:
    driver: bridge
