version: "3.9"

services:
  web:
    build: .
    ports:
      - "8089:3000"
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}

volumes:
  postgres_data:
